services:
  week02:
    image: quay.io/jupyter/pyspark-notebook:2025-12-31
    ports:
      - "8888:8888" # Jupyter UI
      - "4040:4040" # Spark UI (increments for each new SparkContext: 4041, 4042, â€¦)
    volumes:
      - ./work/:/home/jovyan/work  # notebooks, output, and data/ subfolder
    environment:
      - JUPYTER_TOKEN=bdm
    command: start-notebook.py --ServerApp.token=bdm --ServerApp.password='' --ServerApp.allow_origin='*' --ServerApp.allow_remote_access=True
